# Generated by Django 2.1 on 2018-09-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailconfirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmation_key',
            field=models.CharField(max_length=64),
        ),
    ]
